// constants needing to updated every year

export const SEASON_YEAR = 2026;

export const EVENTS = {
  B: [
    "Air Trajectory",
    "Anatomy and Physiology",
    "Boomilever",
    "Bungee Drop",
    "Crime Busters",
    "Circuit Lab",
    "Codebusters",
    "Disease Detectives",
    "Dynamic Planet",
    "Entomology",
    "Experimental Design",
    "Helicopter",
    "Heredity",
    "Hovercraft",
    "Machines",
    "Meteorology",
    "Mission Possible",
    "Potions and Poisons",
    "Remote Sensing",
    "Rocks and Minerals",
    "Scrambler",
    "Solar System",
    "Water Quality",
    "Write It Do It",
  ],
  C: [
    "Anatomy and Physiology",
    "Astronomy",
    "Boomilever",
    "Bungee Drop",
    "Chemistry Lab",
    "Circuit Lab",
    "Codebusters",
    "Designer Genes",
    "Disease Detectives",
    "Dynamic Planet",
    "Electric Vehicle",
    "Engineering CAD",
    "Entomology",
    "Experimental Design",
    "Forensics",
    "Helicopter",
    "Hovercraft",
    "Machines",
    "Materials Science",
    "Remote Sensing",
    "Robot Tour",
    "Rocks and Minerals",
    "Water Quality",
  ],
};

// permanent constants

export const TOURNAMENT_CARDS_PER_PAGE: number = 12;

export const CONTACT_EMAIL = "support@example.com";
export const allowedRedirectBases = ["/profile", "/tournaments"];

export const CALENDAR_START_DATE = new Date(SEASON_YEAR - 1, 0, 1);
export const CALENDAR_END_DATE = new Date(SEASON_YEAR, 11, 31);
export const SEASON_START_DATE = new Date(SEASON_YEAR - 1, 9, 1);
export const SEASON_END_DATE = new Date(SEASON_YEAR, 5, 1);

export const US_STATES = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "Colorado",
  "Connecticut",
  "Delaware",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North California",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South California",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
];
