import { z } from "zod/v4";
import { TournamentInfo } from "./(authenticated)/(volunteers)/tournaments/search/TournamentApplyCard";
import { EditTournamentSchemaClient } from "@/lib/definitions";

export const events = {
  B: [
    "Air Trajectory",
    "Anatomy & Physiology",
    "Boomilever",
    "Bungee Drop",
    "Circuit Lab",
    "Codebusters",
    "Disease Detectives",
    "Dynamic Planet",
    "Entomology",
    "Experimental Design",
    "Helicopter",
    "Heredity",
    "Hovercraft",
    "Machines",
    "Meteorology",
    "Mission Possible",
    "Potions and Poisons",
    "Remote Sensing",
    "Rocks and Minerals",
    "Scrambler",
    "Solar System",
    "Water Quality",
    "Write It Do It",
  ],
  C: [
    "Anatomy & Physiology",
    "Astronomy",
    "Boomilever",
    "Bungee Drop",
    "Chemistry Lab",
    "Circuit Lab",
    "Codebusters",
    "Designer Genes",
    "Disease Detectives",
    "Dynamic Planet",
    "Electric Vehicle",
    "Engineering CAD",
    "Entomology",
    "Experimental Design",
    "Forensics",
    "Helicopter",
    "Hovercraft",
    "Machines",
    "Materials Science",
    "Remote Sensing",
    "Robot Tour",
    "Rocks and Minerals",
    "Water Quality",
  ],
};
export const usStates = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
];

export const tournaments: Array<z.infer<typeof EditTournamentSchemaClient>> = [
  {
    name: "Empire State Invitational",
    startDate: new Date("2026-01-20"),
    endDate: new Date("2026-01-20"),
    applyDeadlineDate: new Date("2025-11-15"),
    applyDeadlineTime: "23:59",
    location: "New York",
    websiteUrl: "https://scilympiad.com/empire",
    division: "C",
    imageUrl: "https://www.duosmium.org/images/logos/empire_state.png",
    closedEarly: false,
  },
  {
    name: "Golden Gate Invitational",
    startDate: new Date("2026-02-10"),
    endDate: new Date("2026-02-10"),
    applyDeadlineDate: new Date("2026-01-10"),
    applyDeadlineTime: "23:59",
    location: "California",
    websiteUrl: "https://scilympiad.com/goldengate",
    division: "C",
    imageUrl:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMwAAADACAMAAAB/Pny7AAAAvVBMVEX///89PT0...", // truncated
    closedEarly: false,
  },
  {
    name: "Midwest Online Invitational",
    startDate: new Date("2026-02-17"),
    endDate: new Date("2026-02-17"),
    applyDeadlineDate: new Date("2026-01-25"),
    applyDeadlineTime: "23:59",
    location: "Online",
    websiteUrl: "https://scilympiad.com/midwest",
    division: "B",
    imageUrl: "https://www.duosmium.org/images/logos/midwest_online.png",
    closedEarly: false,
  },
  {
    name: "JordanSO Invitational",
    startDate: new Date("2026-03-01"),
    endDate: new Date("2026-03-08"),
    applyDeadlineDate: new Date("2026-02-10"),
    applyDeadlineTime: "23:59",
    location: "Online",
    websiteUrl: "https://scilympiad.com/jordan-so",
    division: "B",
    imageUrl: "https://www.duosmium.org/images/logos/jordan_invitational.png",
    closedEarly: false,
  },
  {
    name: "Lone Star Science Olympiad",
    startDate: new Date("2026-04-05"),
    endDate: new Date("2026-04-05"),
    applyDeadlineDate: new Date("2026-03-10"),
    applyDeadlineTime: "23:59",
    location: "Texas",
    websiteUrl: "https://scilympiad.com/lonestar",
    division: "B",
    imageUrl: "https://www.duosmium.org/images/logos/lone_star.png",
    closedEarly: false,
  },
  {
    name: "Pacific Inter-Rim Fake That Probably Doesn't Need to Exist Science Bowl",
    startDate: new Date("2026-05-03"),
    endDate: new Date("2026-05-03"),
    applyDeadlineDate: new Date("2026-04-15"),
    applyDeadlineTime: "23:59",
    location: "Washington",
    websiteUrl: "https://scilympiad.com/pacific",
    division: "C",
    imageUrl: "https://www.duosmium.org/images/logos/pacific_bowl.png",
    closedEarly: false,
  },
];

export let jay = {
  name: "Jay Sahni",
  education: "Jordan HS '26",
  bio: "This is a ton of text that I am testing with no knowledge of if it will work or not.\nThe first law of aviation says that bees should not be able to fly. However, they do.",
  experience:
    "CurdSO Warrior CurdSO Warrior CurdSO Warrior CurdSO Warrior CurdSO Warrior CurdSO Warrior CurdSO Warrior CurdSO Warrior CurdSO Warrior ",
  preferencesB: [
    "Air Trajectory",
    "Rocks and Minerals",
    "Potions and Poisons",
    "Water Quality",
  ],
  preferencesC: [
    "Engineering CAD",
    "Chemistry Lab",
    "Rocks and Minerals",
    "Robot Tour",
  ],
};
export const calendarStartDate = new Date(2025, 0, 1);
export const calendarEndDate = new Date(2026, 11, 31);
export const seasonStartDate = new Date(2025, 9, 1);
export const seasonEndDate = new Date(2026, 5, 1);

export const volunteers = [
  {
    id: "1",
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    education: "MIT '22",
  },
  {
    id: "2",
    name: "Bob Smith",
    email: "bob.smith@example.com",
    education: "Stanford University '21",
  },
  {
    id: "3",
    name: "Carla Nguyen",
    email: "carla.nguyen@example.com",
    education: "Harvard University '23",
  },
  {
    id: "4",
    name: "David Lee",
    email: "david.lee@example.com",
    education: "UC Berkeley '24",
  },
  {
    id: "5",
    name: "Emily Zhang",
    email: "emily.zhang@example.com",
    education: "Columbia University '25",
  },
  {
    id: "6",
    name: "Frank Harris",
    email: "frank.harris@example.com",
    education: "Yale University '22",
  },
  {
    id: "7",
    name: "Grace Kim",
    email: "grace.kim@example.com",
    education: "Princeton University '20",
  },
  {
    id: "8",
    name: "Hassan Ali",
    email: "hassan.ali@example.com",
    education: "University of Chicago '23",
  },
  {
    id: "9",
    name: "Isabelle Martinez",
    email: "isabelle.martinez@example.com",
    education: "Duke University '26",
  },
  {
    id: "10",
    name: "Jason Wu",
    email: "jason.wu@example.com",
    education: "Cornell University '24",
  },
  {
    id: "11",
    name: "Karen Patel",
    email: "karen.patel@example.com",
    education: "Brown University '22",
  },
  {
    id: "12",
    name: "Leo Thompson",
    email: "leo.thompson@example.com",
    education: "Northwestern University '23",
  },
  {
    id: "13",
    name: "Maya Rivera",
    email: "maya.rivera@example.com",
    education: "Johns Hopkins University '25",
  },
  {
    id: "14",
    name: "Nathan Brooks",
    email: "nathan.brooks@example.com",
    education: "Caltech '21",
  },
  {
    id: "15",
    name: "Olivia Chen",
    email: "olivia.chen@example.com",
    education: "University of Pennsylvania '24",
  },
  {
    id: "16",
    name: "Paul Ramirez",
    email: "paul.ramirez@example.com",
    education: "Dartmouth College '22",
  },
  {
    id: "17",
    name: "Queenie Tran",
    email: "queenie.tran@example.com",
    education: "Rice University '26",
  },
  {
    id: "18",
    name: "Raymond Scott",
    email: "raymond.scott@example.com",
    education: "University of Michigan '23",
  },
  {
    id: "19",
    name: "Sophie Davis",
    email: "sophie.davis@example.com",
    education: "University of Virginia '25",
  },
  {
    id: "20",
    name: "Tomoko Sato",
    email: "tomoko.sato@example.com",
    education: "NYU '24",
  },
];
