let events = {
  B: [
    "Air Trajectory",
    "Anatomy & Physiology",
    "Boomilever",
    "Bungee Drop",
    "Circuit Lab",
    "Codebusters",
    "Disease Detectives",
    "Dynamic Planet",
    "Entomology",
    "Experimental Design",
    "Helicopter",
    "Heredity",
    "Hovercraft",
    "Machines",
    "Meteorology",
    "Mission Possible",
    "Potions and Poisons",
    "Remote Sensing",
    "Rocks and Minerals",
    "Scrambler",
    "Solar System",
    "Water Quality",
    "Write It Do It",
  ],
  C: [
    "Anatomy & Physiology",
    "Astronomy",
    "Boomilever",
    "Botany",
    "Bungee Drop",
    "Chemistry Lab",
    "Circuit Lab",
    "Code Craze",
    "Codebusters",
    "Designer Genes",
    "Disease Detectives",
    "Dynamic Planet",
    "Electric Vehicle",
    "Engineering CAD",
    "Entomology",
    "Experimental Design",
    "Forensics",
    "Helicopter",
    "Hovercraft",
    "Machines",
    "Materials Science",
    "Protein Modeling",
    "Remote Sensing",
    "Robot Tour",
    "Rocks and Minerals",
    "Scrambler",
    "Water Quality",
  ],
};
export { events };
