import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../components/shadcn/theme-provider";
import Footer from "@/components/custom/Footer";
import { Toaster } from "sonner";
import { ModeToggle } from "@/components/shadcn/DarkModeToggle";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} w-full min-h-screen flex flex-col 
        before:content-[''] before:fixed before:inset-0 before:-z-10 before:pointer-events-none
        before:animate-grid-scroll before:[will-change:transform]
        before:bg-[linear-gradient(to_right,rgba(0,0,0,0.05)_1px,transparent_1px),linear-gradient(to_bottom,rgba(0,0,0,0.05)_1px,transparent_1px)]
        dark:before:bg-[linear-gradient(to_right,rgba(255,255,255,0.05)_1px,transparent_1px),linear-gradient(to_bottom,rgba(255,255,255,0.05)_1px,transparent_1px)]
        before:bg-[length:30px_30px]
        before:[mask-image:linear-gradient(to_bottom,transparent,black_12%,black_88%,transparent)]
        before:[-webkit-mask-image:linear-gradient(to_bottom,transparent,black_12%,black_88%,transparent)]
        relative`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Toaster />
          {children}
          <Footer />
          <div className="fixed bottom-4 right-4 z-50">
            <ModeToggle />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
